{% set name = "Semi-ATE" %}
{% set version = "0.1.29" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/Semi-ATE-{{ version }}.tar.gz
  sha256: 9e90ff143371336beaa87c1f49638d105a2fd40c957ef06a11c0a307d7062ff6

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7

test:
  imports:
    - ATE
    - ATE.Tester
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/Semi-ATE/
  summary: Framework for Semiconductor ATE testing projects
  license: GPL-2.0-only
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - nerohmot
